export type TextFieldProps = {
  fieldName: string
  label?: string
  toolTipText?: string
  placeholder: string
  formik?: any
  margin?: string
  isForgetPassword?: boolean
  fieldType: string
  isPassword?: boolean
  slug1?: string
  slug2?: string
  linkText1?: string
  linkText2?: string
  customText?: string
  isCheckbox?: boolean
  isFieldArray?: boolean
  isTooltipNotRequired?: boolean
  width?: number
  isBeside?: boolean
  isTooltipRequired?: boolean
  isWidthNotRequired?: boolean
  isDisabled?: boolean
  dateValue?: string
  isSocialMedia?: boolean
  isStarRequired?: boolean
  isRadio?: boolean
  value?: string
  labelWidth?: string
  withoutLabel?: boolean
}
